"""Reviewed follow-up questions, keyed by the passage that answers them.

The questions are written by a local model (`app.gen_suggestions`) but they are
never used straight from it. They are written to a YAML file, read by a human,
committed, and only then picked up by `app.ingest`. Two things fall out of that
detour, and both matter more than the round trip costs:

* nothing the model invented can reach the interface unread, and
* ingest stays deterministic — it reads a file, not a model — so rebuilding the
  index twice produces the same chips both times.

Passages are keyed by file and heading path rather than by `chunk_id`, which is
a content hash and would invalidate every entry on the next typo fix.
"""

from dataclasses import dataclass
from pathlib import Path

import yaml

# Chroma metadata values must be scalars, so the questions travel as one string.
# A newline is safe: `clean_question` rejects anything containing one.
QUESTION_SEPARATOR = "\n"


@dataclass(frozen=True)
class PassageKey:
    """Identifies the passage a set of follow-up questions belongs to."""

    file: str
    section: str


def clean_question(line: str) -> str | None:
    """Normalise one generated line, or reject it.

    The prompt forbids numbering, bullets and quotes, but a local model obeys
    formatting instructions imperfectly and this output is committed to the
    repository. Stripping the usual decorations here keeps the reviewer looking
    at questions rather than at list markup.
    """
    text = line.strip().strip("\"'").strip()
    while text[:1] in {"-", "*", "•"}:
        text = text[1:].strip()
    # Leading "1." / "2)" style numbering.
    digits = 0
    while digits < len(text) and text[digits].isdigit():
        digits += 1
    if digits and text[digits : digits + 1] in {".", ")"}:
        text = text[digits + 1 :].strip()

    if not text.endswith("?") or len(text) < 8 or "\n" in text:
        return None
    return text


def load(path: Path) -> dict[PassageKey, list[str]]:
    """Read the reviewed questions. Missing file means no suggestions."""
    if not path.exists():
        return {}

    document = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    entries = document.get("passages") or []
    return {
        PassageKey(file=str(entry["file"]), section=str(entry["section"])): [
            question
            for line in entry.get("questions", []) or []
            if (question := clean_question(str(line)))
        ]
        for entry in entries
    }


def dump(path: Path, questions: dict[PassageKey, list[str]]) -> None:
    """Write the questions in the shape `load` expects, sorted for stable diffs."""
    payload = {
        "passages": [
            {
                "file": key.file,
                "section": key.section,
                "questions": questions[key],
            }
            for key in sorted(questions, key=lambda k: (k.file, k.section))
        ]
    }
    header = (
        "# Follow-up questions offered as chips after an answer.\n"
        "#\n"
        "# Generated by `uv run python -m app.gen_suggestions`, then reviewed by\n"
        "# hand before being committed. `app.ingest` reads this file, never the\n"
        "# model, so the questions shown in the interface are always ones a\n"
        "# person has read.\n"
        "#\n"
        "# Every question must be answerable from its own passage. Editing or\n"
        "# deleting a line here is expected; re-run ingest afterwards.\n"
    )
    path.write_text(
        header + yaml.safe_dump(payload, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )
